resolver: lts-9.6
packages:
  - ./common
  - ./examples/lesson01
  - ./examples/lesson02
  - ./examples/lesson03
  - ./examples/lesson04
  - ./examples/lesson05

extra-deps: []

flags: {}

extra-package-dbs: []
