resolver: lts-9.6
packages:
  - ./common
  - ./examples/lesson01
  - ./examples/lesson02
  - ./examples/lesson03
  - ./examples/lesson04
  - ./examples/lesson05
  - ./examples/lesson06
  - ./examples/lesson07
  - ./examples/lesson08
  - ./examples/lesson13
  - ./examples/lesson14

extra-deps: []

flags: {}

extra-package-dbs: []
